[package]
name = "ferrite-core"
version = "0.2.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
atomic = { version = "0.5.1", default-features = false }
futures = "0.3.25"
stavec = { version = "0.2.1", features = ["repr-c"] }
log = "0.4"
derive_more = "0.99.17"
