[package]
name = "ferrite-core"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
atomic_enum = "0.2.0"
futures = "0.3.25"
stavec = { version = "0.2.0", features = ["repr-c"] }
log = "0.4"

[dev-dependencies]
async-std = "1.12.0"
async-ringbuf = "0.1.0"
